//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Servicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informacoes_Moedas
    {
        public int Cod_Moeda { get; set; }
        public string Tipo { get; set; }
        public string Moeda { get; set; }
        public double Taxa_Compra { get; set; }
        public double Taxa_Venda { get; set; }
        public double Paridade_Compra { get; set; }
        public double Paridade_Venda { get; set; }
    }
}
